#!/usr/bin/env python3
"""
C2 Profile Gen — Malleable C2 Profile Generator for Cobalt Strike / Havoc
Generates randomized, realistic-looking profiles to blend C2 traffic into legitimate web traffic.
Author: Omar Khalid (amooryx) | github.com/amooryx/c2-profile-gen
AUTHORIZED USE ONLY — for licensed red team engagements.
"""

import argparse
import json
import random
import string
import sys
from datetime import datetime

# ─── Legitimate-looking URI patterns ─────────────────────────────────────────
URI_PATTERNS = {
    "cdn":    ["/cdn-cgi/challenge-platform/h/b/orchestrate/jsfm/visits", "/cdn-cgi/zaraz/s.js",
               "/cdn/static/app-{rand}.js", "/assets/js/vendor-{rand}.js"],
    "api":    ["/api/v2/events", "/api/v{n}/telemetry", "/api/analytics/collect",
               "/graphql", "/api/auth/token/refresh"],
    "update": ["/update/check", "/software/update/catalog", "/update/manifest.json",
               "/autoupdate/v1/check"],
    "pixel":  ["/pixel.gif", "/t.gif", "/tracker", "/collect",
               "/p.gif?cid={rand}&t=pageview"],
    "office": ["/autodiscover/autodiscover.xml", "/ews/exchange.asmx",
               "/mapi/emsmdb/", "/EWS/Exchange.asmx"],
}

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15",
    "Microsoft Office/16.0 (Windows NT 10.0; Microsoft Outlook 16.0; Pro)",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0",
]

HOST_PROFILES = {
    "cdn":    ["cdnjs.cloudflare.com", "cdn.jsdelivr.net", "fonts.googleapis.com", "staticxx.facebook.com"],
    "api":    ["api.amplitude.com", "api.mixpanel.com", "cdn.segment.io", "events.launchdarkly.com"],
    "update": ["update.microsoft.com", "software-update.apple.com", "download.mozilla.org"],
    "office": ["outlook.office365.com", "autodiscover-s.outlook.com", "smtp.office365.com"],
}

def rand_str(n: int = 8) -> str:
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=n))

def make_uri(pattern: str) -> str:
    return pattern.replace("{rand}", rand_str()).replace("{n}", str(random.randint(1, 5)))

# ─── Profile generators ───────────────────────────────────────────────────────
def generate_cobalt_strike(profile_type: str, jitter: int, sleep: int) -> str:
    uris = [make_uri(p) for p in random.sample(URI_PATTERNS.get(profile_type, URI_PATTERNS["cdn"]), 2)]
    host = random.choice(HOST_PROFILES.get(profile_type, HOST_PROFILES["cdn"]))
    ua   = random.choice(USER_AGENTS)

    lines = [
        f"# Generated by c2-profile-gen | {datetime.now().isoformat()}",
        f"# Profile type: {profile_type} | For authorized use only",
        "",
        f"set sleeptime \"{sleep * 1000}\";",
        f"set jitter     \"{jitter}\";",
        f"set maxdns      \"255\";",
        f"set useragent  \"{ua}\";",
        "",
        "http-get {",
        f"    set uri \"{uris[0]}\";",
        "    client {",
        f"        header \"Host\" \"{host}\";",
        "        header \"Accept\" \"*/*\";",
        "        header \"Accept-Language\" \"en-US,en;q=0.9\";",
        "        header \"Referer\" \"https://" + host + "/\";",
        "        metadata {",
        "            base64url;",
        "            prepend \"session=\";",
        "            header \"Cookie\";",
        "        }",
        "    }",
        "    server {",
        "        header \"Content-Type\" \"application/javascript\";",
        "        header \"Cache-Control\" \"public, max-age=31536000\";",
        "        output { base64url; print; }",
        "    }",
        "}",
        "",
        "http-post {",
        f"    set uri \"{uris[1]}\";",
        "    client {",
        f"        header \"Host\" \"{host}\";",
        "        header \"Content-Type\" \"application/json\";",
        "        id { base64url; prepend \"uid=\"; parameter \"_\"; }",
        "        output { base64; print; }",
        "    }",
        "    server {",
        "        header \"Content-Type\" \"application/json\";",
        "        output { base64; print; }",
        "    }",
        "}",
    ]
    return "\n".join(lines)

def generate_havoc(profile_type: str, jitter: int, sleep: int) -> str:
    uris = [make_uri(p) for p in random.sample(URI_PATTERNS.get(profile_type, URI_PATTERNS["api"]), 2)]
    host = random.choice(HOST_PROFILES.get(profile_type, HOST_PROFILES["api"]))
    ua   = random.choice(USER_AGENTS)

    profile = {
        "Profile": {
            "Type": "https",
            "Sleep": sleep,
            "Jitter": jitter,
            "UserAgent": ua,
            "Headers": [
                {"Name": "Host",            "Value": host},
                {"Name": "Accept",          "Value": "application/json, text/plain, */*"},
                {"Name": "Accept-Language", "Value": "en-US,en;q=0.5"},
            ],
            "Uris": uris,
            "Comment": f"Generated by c2-profile-gen | {datetime.now().isoformat()} | AUTHORIZED USE ONLY",
        }
    }
    return json.dumps(profile, indent=2)

# ─── Entry ────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description="C2 Profile Gen — Malleable C2 Profile Generator (Authorized use only)",
    )
    parser.add_argument("--framework", choices=["cobalt-strike", "havoc"], default="cobalt-strike",
                        help="Target C2 framework")
    parser.add_argument("--type",      choices=list(URI_PATTERNS.keys()),  default="cdn",
                        help="Traffic profile type")
    parser.add_argument("--sleep",     type=int, default=60,  help="Sleep interval (seconds)")
    parser.add_argument("--jitter",    type=int, default=20,  help="Jitter percentage (0-100)")
    parser.add_argument("--out",       help="Output file (stdout if omitted)")
    args = parser.parse_args()

    if args.framework == "cobalt-strike":
        profile = generate_cobalt_strike(args.type, args.jitter, args.sleep)
        ext = ".profile"
    else:
        profile = generate_havoc(args.type, args.jitter, args.sleep)
        ext = ".json"

    if args.out:
        fname = args.out if args.out.endswith(ext) else args.out + ext
        with open(fname, "w") as f:
            f.write(profile)
        print(f"[+] Profile written to: {fname}")
    else:
        print(profile)

if __name__ == "__main__":
    main()
